all:
	mpiCC main/Main.cpp \
	solvers/seidel/Seidel.cpp \
	solvers/jacobi/JacobiV1.cpp \
	solvers/jacobi/JacobiV2.cpp \
	solvers/jacobi/JacobiV3.cpp \
	solvers/jacobi/JacobiCommon.cpp \
	common/Common.cpp \
	-o compiled/lab3.out
