all:
	mpiCC main/Main.cpp \
	solvers/jacobi/JacobiV1.cpp \
	solvers/jacobi/JacobiV2.cpp \
	solvers/jacobi/JacobiV3.cpp \
	solvers/jacobi/JacobiCommon.cpp \
	solvers/seidel/SeidelV1.cpp \
	solvers/seidel/SeidelV2.cpp \
	solvers/seidel/SeidelV3.cpp \
	solvers/seidel/SeidelCommon.cpp \
	common/Common.cpp \
	common/Logging.cpp \
	common/DataExchanging.cpp \
	-o compiled/lab3.out
